"""Generated schema dictionaries for step02 (string types)."""

complete_domain_schema_dict = {
    'condition': {
        'conditionid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'report_date': 'date',
        'resolve_date': 'date',
        'onset_date': 'date',
        'condition_status': 'string',
        'condition': 'string',
        'condition_type': 'string',
        'condition_source': 'string',
        'raw_condition_status': 'string',
        'raw_condition': 'string',
        'raw_condition_type': 'string',
        'raw_condition_source': 'string',
    },
    'control_map': {
        'case_patid': 'string',
        'buddy_num': 'int',
        'control_patid': 'string',
        'case_age': 'int',
        'case_sex': 'string',
        'case_race': 'string',
        'case_ethn': 'string',
        'control_age': 'int',
        'control_sex': 'string',
        'control_race': 'string',
        'control_ethn': 'string',
    },
    'death': {
        'patid': 'string',
        'death_date': 'date',
        'death_date_impute': 'string',
        'death_source': 'string',
        'death_match_confidence': 'string',
    },
    'death_cause': {
        'patid': 'string',
        'death_cause': 'string',
        'death_cause_code': 'string',
        'death_cause_type': 'string',
        'death_cause_source': 'string',
        'death_cause_confidence': 'string',
    },
    'demographic': {
        'patid': 'string',
        'birth_date': 'date',
        'birth_time': 'string',
        'sex': 'string',
        'sexual_orientation': 'string',
        'gender_identity': 'string',
        'hispanic': 'string',
        'race': 'string',
        'biobank_flag': 'string',
        'pat_pref_language_spoken': 'string',
        'raw_sex': 'string',
        'raw_sexual_orientation': 'string',
        'raw_gender_identity': 'string',
        'raw_hispanic': 'string',
        'raw_race': 'string',
        'raw_pat_pref_language_spoken': 'string',
    },
    'diagnosis': {
        'diagnosisid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'enc_type': 'string',
        'admit_date': 'date',
        'providerid': 'string',
        'dx': 'string',
        'dx_type': 'string',
        'dx_date': 'date',
        'dx_source': 'string',
        'dx_origin': 'string',
        'pdx': 'string',
        'dx_poa': 'string',
        'raw_dx': 'string',
        'raw_dx_type': 'string',
        'raw_dx_source': 'string',
        'raw_pdx': 'string',
        'raw_dx_poa': 'string',
    },
    'dispensing': {
        'dispensingid': 'string',
        'patid': 'string',
        'prescribingid': 'string',
        'dispense_date': 'date',
        'ndc': 'string',
        'dispense_source': 'string',
        'dispense_sup': 'double',
        'dispense_amt': 'double',
        'dispense_dose_disp': 'double',
        'dispense_dose_disp_unit': 'string',
        'dispense_route': 'string',
        'raw_ndc': 'string',
        'raw_dispense_dose_disp': 'string',
        'raw_dispense_dose_disp_unit': 'string',
        'raw_dispense_route': 'string',
    },
    'encounter': {
        'encounterid': 'string',
        'patid': 'string',
        'admit_date': 'date',
        'admit_time': 'string',
        'discharge_date': 'date',
        'discharge_time': 'string',
        'providerid': 'string',
        'facility_location': 'string',
        'enc_type': 'string',
        'facilityid': 'string',
        'discharge_disposition': 'string',
        'discharge_status': 'string',
        'drg': 'string',
        'drg_type': 'string',
        'admitting_source': 'string',
        'payer_type_primary': 'string',
        'payer_type_secondary': 'string',
        'facility_type': 'string',
        'raw_siteid': 'string',
        'raw_enc_type': 'string',
        'raw_discharge_disposition': 'string',
        'raw_discharge_status': 'string',
        'raw_drg_type': 'string',
        'raw_admitting_source': 'string',
        'raw_facility_type': 'string',
        'raw_payer_type_primary': 'string',
        'raw_payer_name_primary': 'string',
        'raw_payer_id_primary': 'string',
        'raw_payer_type_secondary': 'string',
        'raw_payer_name_secondary': 'string',
        'raw_payer_id_secondary': 'string',
    },
    'immunization': {
        'immunizationid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'proceduresid': 'string',
        'vx_providerid': 'string',
        'vx_record_date': 'date',
        'vx_admin_date': 'date',
        'vx_code_type': 'string',
        'vx_code': 'string',
        'vx_status': 'string',
        'vx_status_reason': 'string',
        'vx_source': 'string',
        'vx_dose': 'double',
        'vx_dose_unit': 'string',
        'vx_route': 'string',
        'vx_body_site': 'string',
        'vx_manufacturer': 'string',
        'vx_lot_num': 'string',
        'vx_exp_date': 'date',
        'raw_vx_name': 'string',
        'raw_vx_code': 'string',
        'raw_vx_code_type': 'string',
        'raw_vx_dose': 'string',
        'raw_vx_dose_unit': 'string',
        'raw_vx_route': 'string',
        'raw_vx_body_site': 'string',
        'raw_vx_status': 'string',
        'raw_vx_status_reason': 'string',
        'raw_vx_manufacturer': 'string',
    },
    'lab_result_cm': {
        'lab_result_cm_id': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'specimen_source': 'string',
        'lab_loinc': 'string',
        'lab_result_source': 'string',
        'lab_loinc_source': 'string',
        'priority': 'string',
        'result_loc': 'string',
        'lab_px': 'string',
        'lab_px_type': 'string',
        'lab_order_date': 'date',
        'specimen_date': 'date',
        'specimen_time': 'string',
        'result_date': 'date',
        'result_time': 'string',
        'result_qual': 'string',
        'result_snomed': 'string',
        'result_num': 'double',
        'result_modifier': 'string',
        'result_unit': 'string',
        'norm_range_low': 'string',
        'norm_modifier_low': 'string',
        'norm_range_high': 'string',
        'norm_modifier_high': 'string',
        'abn_ind': 'string',
        'raw_lab_name': 'string',
        'raw_lab_code': 'string',
        'raw_panel': 'string',
        'raw_result': 'string',
        'raw_unit': 'string',
        'raw_order_dept': 'string',
        'raw_facility_code': 'string',
    },
    'lds_address_history': {
        'addressid': 'string',
        'patid': 'string',
        'address_use': 'string',
        'address_type': 'string',
        'address_preferred': 'string',
        'address_city': 'string',
        'address_state': 'string',
        'address_zip5': 'string',
        'address_zip9': 'string',
        'address_county': 'string',
        'address_period_start': 'date',
        'address_period_end': 'date',
    },
    'med_admin': {
        'medadminid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'prescribingid': 'string',
        'medadmin_providerid': 'string',
        'medadmin_start_date': 'date',
        'medadmin_start_time': 'string',
        'medadmin_stop_date': 'date',
        'medadmin_stop_time': 'string',
        'medadmin_type': 'string',
        'medadmin_code': 'string',
        'medadmin_dose_admin': 'double',
        'medadmin_dose_admin_unit': 'string',
        'medadmin_route': 'string',
        'medadmin_source': 'string',
        'raw_medadmin_med_name': 'string',
        'raw_medadmin_code': 'string',
        'raw_medadmin_dose_admin': 'string',
        'raw_medadmin_dose_admin_unit': 'string',
        'raw_medadmin_route': 'string',
    },
    'note': {
        'note_id': 'bigint',
        'person_id': 'string',
        'note_date': 'date',
        'note_datetime': 'timestamp',
        'note_type_concept_id': 'int',
        'note_class_concept_id': 'int',
        'note_title': 'string',
        'note_text': 'string',
        'encoding_concept_id': 'int',
        'language_concept_id': 'int',
        'provider_id': 'int',
        'visit_occurrence_id': 'int',
        'visit_detail_id': 'int',
        'note_source_value': 'string',
    },
    'note_nlp': {
        'note_nlp_id': 'bigint',
        'note_id': 'bigint',
        'section_concept_id': 'int',
        'snippet': 'string',
        'offset': 'string',
        'lexical_variant': 'string',
        'note_nlp_concept_id': 'int',
        'note_nlp_source_concept_id': 'int',
        'nlp_system': 'string',
        'nlp_date': 'date',
        'nlp_datetime': 'timestamp',
        'term_exists': 'string',
        'term_temporal': 'string',
        'term_modifiers': 'string',
    },
    'obs_clin': {
        'obsclinid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'obsclin_providerid': 'string',
        'obsclin_start_date': 'date',
        'obsclin_start_time': 'string',
        'obsclin_stop_date': 'date',
        'obsclin_stop_time': 'string',
        'obsclin_type': 'string',
        'obsclin_code': 'string',
        'obsclin_result_qual': 'string',
        'obsclin_result_text': 'string',
        'obsclin_result_snomed': 'string',
        'obsclin_result_num': 'double',
        'obsclin_result_modifier': 'string',
        'obsclin_result_unit': 'string',
        'obsclin_source': 'string',
        'obsclin_abn_ind': 'string',
        'raw_obsclin_name': 'string',
        'raw_obsclin_code': 'string',
        'raw_obsclin_type': 'string',
        'raw_obsclin_result': 'string',
        'raw_obsclin_modifier': 'string',
        'raw_obsclin_unit': 'string',
    },
    'obs_clin_5.0': {
        'obsclinid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'obsclin_providerid': 'string',
        'obsclin_date': 'date',
        'obsclin_time': 'string',
        'obsclin_type': 'string',
        'obsclin_code': 'string',
        'obsclin_result_qual': 'string',
        'obsclin_result_text': 'string',
        'obsclin_result_snomed': 'string',
        'obsclin_result_num': 'double',
        'obsclin_result_modifier': 'string',
        'obsclin_result_unit': 'string',
        'obsclin_source': 'string',
        'obsclin_abn_ind': 'string',
        'raw_obsclin_name': 'string',
        'raw_obsclin_code': 'string',
        'raw_obsclin_type': 'string',
        'raw_obsclin_result': 'string',
        'raw_obsclin_modifier': 'string',
        'raw_obsclin_unit': 'string',
    },
    'obs_gen': {
        'obsgenid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'obsgen_providerid': 'string',
        'obsgen_start_date': 'date',
        'obsgen_start_time': 'string',
        'obsgen_stop_date': 'date',
        'obsgen_stop_time': 'string',
        'obsgen_type': 'string',
        'obsgen_code': 'string',
        'obsgen_result_qual': 'string',
        'obsgen_result_text': 'string',
        'obsgen_result_num': 'double',
        'obsgen_result_modifier': 'string',
        'obsgen_result_unit': 'string',
        'obsgen_table_modified': 'string',
        'obsgen_id_modified': 'string',
        'obsgen_source': 'string',
        'obsgen_abn_ind': 'string',
        'raw_obsgen_name': 'string',
        'raw_obsgen_code': 'string',
        'raw_obsgen_type': 'string',
        'raw_obsgen_result': 'string',
        'raw_obsgen_unit': 'string',
    },
    'obs_gen_5.0': {
        'obsgenid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'obsgen_providerid': 'string',
        'obsgen_date': 'date',
        'obsgen_time': 'string',
        'obsgen_type': 'string',
        'obsgen_code': 'string',
        'obsgen_result_qual': 'string',
        'obsgen_result_text': 'string',
        'obsgen_result_num': 'double',
        'obsgen_result_modifier': 'string',
        'obsgen_result_unit': 'string',
        'obsgen_table_modified': 'string',
        'obsgen_id_modified': 'string',
        'obsgen_source': 'string',
        'obsgen_abn_ind': 'string',
        'raw_obsgen_name': 'string',
        'raw_obsgen_code': 'string',
        'raw_obsgen_type': 'string',
        'raw_obsgen_result': 'string',
        'raw_obsgen_unit': 'string',
    },
    'prescribing': {
        'prescribingid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'rx_providerid': 'string',
        'rx_order_date': 'date',
        'rx_order_time': 'string',
        'rx_start_date': 'date',
        'rx_end_date': 'date',
        'rx_dose_ordered': 'double',
        'rx_dose_ordered_unit': 'string',
        'rx_quantity': 'double',
        'rx_dose_form': 'string',
        'rx_refills': 'double',
        'rx_days_supply': 'double',
        'rx_frequency': 'string',
        'rx_prn_flag': 'string',
        'rx_route': 'string',
        'rx_basis': 'string',
        'rxnorm_cui': 'string',
        'rx_source': 'string',
        'rx_dispense_as_written': 'string',
        'raw_rx_med_name': 'string',
        'raw_rx_frequency': 'string',
        'raw_rxnorm_cui': 'string',
        'raw_rx_quantity': 'string',
        'raw_rx_ndc': 'string',
        'raw_rx_dose_ordered': 'string',
        'raw_rx_dose_ordered_unit': 'string',
        'raw_rx_route': 'string',
        'raw_rx_refills': 'string',
    },
    'pro_cm': {
        'pro_cm_id': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'pro_date': 'date',
        'pro_time': 'string',
        'pro_type': 'string',
        'pro_item_name': 'string',
        'pro_item_loinc': 'string',
        'pro_response_text': 'string',
        'pro_response_num': 'double',
        'pro_method': 'string',
        'pro_mode': 'string',
        'pro_cat': 'string',
        'pro_source': 'string',
        'pro_item_version': 'string',
        'pro_measure_name': 'string',
        'pro_measure_seq': 'string',
        'pro_measure_score': 'double',
        'pro_measure_theta': 'double',
        'pro_measure_scaled_tscore': 'double',
        'pro_measure_standard_error': 'double',
        'pro_measure_count_scored': 'double',
        'pro_measure_loinc': 'string',
        'pro_measure_version': 'string',
        'pro_item_fullname': 'string',
        'pro_item_text': 'string',
        'pro_measure_fullname': 'string',
    },
    'pro_cm_v7': {
        'pro_code': 'string',
        'pro_cm_id': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'pro_date': 'date',
        'pro_time': 'string',
        'pro_type': 'string',
        'pro_item_name': 'string',
        'pro_response_text': 'string',
        'pro_response_num': 'double',
        'pro_method': 'string',
        'pro_mode': 'string',
        'pro_cat': 'string',
        'pro_source': 'string',
        'pro_item_version': 'string',
        'pro_measure_seq': 'string',
        'pro_item_fullname': 'string',
        'pro_item_text': 'string',
        'pro_measure_loinc': 'string',
        'pro_item_loinc': 'string',
    },
    'procedures': {
        'proceduresid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'enc_type': 'string',
        'admit_date': 'date',
        'providerid': 'string',
        'px_date': 'date',
        'px': 'string',
        'px_type': 'string',
        'px_source': 'string',
        'ppx': 'string',
        'raw_px': 'string',
        'raw_px_type': 'string',
        'raw_ppx': 'string',
    },
    'provider': {
        'providerid': 'string',
        'provider_sex': 'string',
        'provider_specialty_primary': 'string',
        'provider_npi': 'double',
        'provider_npi_flag': 'string',
        'raw_provider_specialty_primary': 'string',
    },
    'vital': {
        'vitalid': 'string',
        'patid': 'string',
        'encounterid': 'string',
        'measure_date': 'date',
        'measure_time': 'string',
        'vital_source': 'string',
        'ht': 'double',
        'wt': 'double',
        'diastolic': 'double',
        'systolic': 'double',
        'original_bmi': 'double',
        'bp_position': 'string',
        'smoking': 'string',
        'tobacco': 'string',
        'tobacco_type': 'string',
        'raw_diastolic': 'string',
        'raw_systolic': 'string',
        'raw_bp_position': 'string',
        'raw_smoking': 'string',
        'raw_tobacco': 'string',
        'raw_tobacco_type': 'string',
    },
}

required_domain_schema_dict = {
    'condition': [
        'conditionid',
        'patid',
        'condition',
        'condition_type',
        'condition_source',
    ],
    'control_map': [
        'case_patid',
        'buddy_num',
        'control_patid',
    ],
    'death': [
        'patid',
        'death_source',
    ],
    'death_cause': [
        'patid',
        'death_cause',
        'death_cause_code',
        'death_cause_type',
        'death_cause_source',
    ],
    'demographic': [
        'patid',
    ],
    'diagnosis': [
        'diagnosisid',
        'patid',
        'dx',
        'dx_type',
        'dx_source',
    ],
    'dispensing': [
        'dispensingid',
        'patid',
        'dispense_date',
        'ndc',
    ],
    'encounter': [
        'encounterid',
        'patid',
        'admit_date',
        'enc_type',
    ],
    'immunization': [
        'patid',
        'vx_code',
        'vx_code_type',
        'vx_status',
    ],
    'lab_result_cm': [
        'lab_result_cm_id',
        'patid',
        'result_date',
    ],
    'lds_address_history': [
        'patid',
        'address_use',
        'address_type',
        'address_preferred',
    ],
    'med_admin': [
        'medadminid',
        'patid',
        'medadmin_start_date',
    ],
    'note': [
    ],
    'note_nlp': [
    ],
    'obs_clin': [
        'obsclinid',
        'patid',
        'obsclin_start_date',
    ],
    'obs_clin_5.0': [
        'obsclinid',
        'patid',
        'obsclin_date',
    ],
    'obs_gen': [
        'obsgenid',
        'patid',
        'obsgen_start_date',
    ],
    'obs_gen_5.0': [
        'obsgenid',
        'patid',
        'obsgen_date',
    ],
    'prescribing': [
        'prescribingid',
        'patid',
    ],
    'pro_cm': [
        'pro_cm_id',
        'patid',
        'pro_date',
    ],
    'pro_cm_v7': [
        'pro_cm_id',
        'pro_code',
        'patid',
        'pro_date',
    ],
    'procedures': [
        'proceduresid',
        'patid',
        'px',
        'px_type',
    ],
    'provider': [
        'providerid',
    ],
    'vital': [
        'vitalid',
        'patid',
        'measure_date',
        'vital_source',
    ],
}
